# Site settings
author: Ethan Lee-Tyson
title: Beginner's Mind
header-img: img/home-bg.png
email: eleetyson@gmail.com
copyright_name: Ethan Lee-Tyson
description: > # this means to ignore newlines until "baseurl:"
  on debugging my code and brain
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eleetyson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
